import type { Product, TherapeuticArea, NewsArticle, JobOpening } from './supabase';

export const defaultTherapeuticAreas: TherapeuticArea[] = [
  { id: 'ta-1', name: 'Cardiology', slug: 'cardiology', description: 'Comprehensive medications for hypertension, heart failure, lipid management, and cardiovascular wellness.', icon: 'HeartPulse', display_order: 1 },
  { id: 'ta-2', name: 'Diabetes & Metabolism', slug: 'diabetes', description: 'Advanced glycemic control formulations, insulin sensitizers, and metabolic health solutions.', icon: 'Activity', display_order: 2 },
  { id: 'ta-3', name: 'Gastroenterology', slug: 'gastroenterology', description: 'Proton pump inhibitors, anti-ulcerants, and digestive system treatments.', icon: 'CircleDot', display_order: 3 },
  { id: 'ta-4', name: 'Respiratory Medicine', slug: 'respiratory', description: 'Bronchodilators, anti-asthmatics, and respiratory infection therapy formulations.', icon: 'Wind', display_order: 4 },
  { id: 'ta-5', name: 'Dermatology', slug: 'dermatology', description: 'Topical steroids, anti-fungal treatments, and advanced dermatological care.', icon: 'Shield', display_order: 5 },
  { id: 'ta-6', name: 'Neurology & CNS', slug: 'neurology', description: 'Neuroprotective agents, anticonvulsants, and central nervous system therapeutics.', icon: 'Brain', display_order: 6 },
  { id: 'ta-7', name: 'Orthopedics', slug: 'orthopedics', description: 'NSAIDs, bone health supplements, and anti-inflammatory musculoskeletal treatments.', icon: 'Bone', display_order: 7 },
  { id: 'ta-8', name: 'Anti-Infectives', slug: 'anti-infectives', description: 'Broad-spectrum antibiotics, anti-virals, and critical care anti-infective formulations.', icon: 'ShieldPlus', display_order: 8 },
  { id: 'ta-9', name: "Women's Health", slug: 'womens-health', description: 'Hormonal therapies, prenatal care formulations, and gynecology treatments.', icon: 'HeartPulse', display_order: 9 },
  { id: 'ta-10', name: 'Pain Management', slug: 'pain-management', description: 'Analgesics, muscle relaxants, and targeted pain relief medications.', icon: 'Pill', display_order: 10 },
  { id: 'ta-11', name: 'Nutraceuticals', slug: 'nutraceuticals', description: 'Essential vitamins, trace minerals, and clinical nutritional supplements.', icon: 'Leaf', display_order: 11 },
  { id: 'ta-12', name: 'General Healthcare', slug: 'general-healthcare', description: 'Essential prescription medicines and wellness formulations for broad clinical use.', icon: 'PlusCircle', display_order: 12 },
];

export const defaultProducts: Product[] = [
  {
    id: 'prod-1',
    name: 'AmoxiShaw 500 Tablets',
    slug: 'amoxishaw-500-tablets',
    product_code: 'SHA-ANT-001',
    composition: 'Amoxicillin Trihydrate IP 500mg',
    dosage_form: 'Film-Coated Tablet',
    strength: '500mg',
    packaging: '10 x 10 Blister Pack',
    category: 'Prescription Antibiotic',
    therapeutic_area: 'Anti-Infectives',
    product_type: 'Branded Generic',
    image_url: null,
    indications: 'Indicated for upper & lower respiratory tract infections, urinary tract infections, and skin/soft tissue infections caused by susceptible organisms.',
    storage: 'Store below 25°C in a dry place. Protect from light.',
    product_info: 'AmoxiShaw 500 delivers rapid bactericidal action with excellent bio-availability and consistent therapeutic efficacy.',
    is_featured: true,
    display_order: 1,
  },
  {
    id: 'prod-2',
    name: 'CardiaShaw 10 mg',
    slug: 'cardiashaw-10-mg',
    product_code: 'SHA-CAR-002',
    composition: 'Amlodipine Besylate IP 10mg',
    dosage_form: 'Tablet',
    strength: '10mg',
    packaging: '10 x 14 Aluminium Blister',
    category: 'Antihypertensive',
    therapeutic_area: 'Cardiology',
    product_type: 'Cardiovascular',
    image_url: null,
    indications: 'Management of essential hypertension, chronic stable angina, and vasospastic angina.',
    storage: 'Store in a cool, dry place away from direct sunlight.',
    product_info: 'CardiaShaw 10 offers smooth 24-hour blood pressure control with high patient compliance and low incidence of peripheral edema.',
    is_featured: true,
    display_order: 2,
  },
  {
    id: 'prod-3',
    name: 'GlyceShaw SR 500',
    slug: 'glyceshaw-sr-500',
    product_code: 'SHA-DIA-003',
    composition: 'Metformin Hydrochloride Sustained Release 500mg',
    dosage_form: 'Sustained-Release Tablet',
    strength: '500mg',
    packaging: '10 x 10 Strip Pack',
    category: 'Anti-Diabetic',
    therapeutic_area: 'Diabetes & Metabolism',
    product_type: 'Endocrinology',
    image_url: null,
    indications: 'First-line therapy for type 2 diabetes mellitus, particularly in overweight patients when dietary management fails.',
    storage: 'Store below 30°C. Protect from moisture.',
    product_info: 'Sustained release formulation ensures steady glycemic control with reduced gastrointestinal adverse events.',
    is_featured: true,
    display_order: 3,
  },
  {
    id: 'prod-4',
    name: 'GastroShaw 20 Capsules',
    slug: 'gastroshaw-20-capsules',
    product_code: 'SHA-GAS-004',
    composition: 'Omeprazole IP 20mg (Enteric Coated Pellets)',
    dosage_form: 'Hard Gelatin Capsule',
    strength: '20mg',
    packaging: '10 x 10 Alu-Alu Strip',
    category: 'Proton Pump Inhibitor',
    therapeutic_area: 'Gastroenterology',
    product_type: 'GI Care',
    image_url: null,
    indications: 'Gastroesophageal reflux disease (GERD), duodenal & gastric ulcers, Zollinger-Ellison syndrome.',
    storage: 'Store at temperatures not exceeding 25°C in a dry place.',
    product_info: 'Provides potent gastric acid suppression to facilitate rapid ulcer healing and heartburn relief.',
    is_featured: true,
    display_order: 4,
  },
  {
    id: 'prod-5',
    name: 'NeuroShaw 50',
    slug: 'neuroshaw-50',
    product_code: 'SHA-NEU-005',
    composition: 'Sertraline Hydrochloride IP 50mg',
    dosage_form: 'Film-Coated Tablet',
    strength: '50mg',
    packaging: '10 x 10 Blister Pack',
    category: 'SSRI Antidepressant',
    therapeutic_area: 'Neurology & CNS',
    product_type: 'Neuro-Psychiatry',
    image_url: null,
    indications: 'Major depressive disorder, panic disorder, obsessive-compulsive disorder (OCD), and social anxiety disorder.',
    storage: 'Store below 25°C.',
    product_info: 'High selectivity for serotonin reuptake with established efficacy and favorable tolerability profile.',
    is_featured: false,
    display_order: 5,
  },
  {
    id: 'prod-6',
    name: 'RespiShaw Inhaler',
    slug: 'respishaw-inhaler',
    product_code: 'SHA-RES-006',
    composition: 'Salbutamol Sulphate IP 100mcg per actuation',
    dosage_form: 'Metered Dose Inhaler',
    strength: '100mcg',
    packaging: 'Canister of 200 Doses',
    category: 'Bronchodilator',
    therapeutic_area: 'Respiratory Medicine',
    product_type: 'Pulmonology',
    image_url: null,
    indications: 'Relief and prevention of bronchospasm in bronchial asthma, chronic bronchitis, and emphysema.',
    storage: 'Store below 30°C. Protect from frost and direct sunlight.',
    product_info: 'Fast-acting beta-2 agonist delivering rapid airway relief within minutes of inhalation.',
    is_featured: false,
    display_order: 6,
  },
  {
    id: 'prod-7',
    name: 'DermaShaw Cream',
    slug: 'dermashaw-cream',
    product_code: 'SHA-DER-007',
    composition: 'Hydrocortisone 1% w/w & Clotrimazole 1% w/w',
    dosage_form: 'Topical Cream',
    strength: '1% + 1%',
    packaging: '30g Laminated Tube',
    category: 'Dermatological Cream',
    therapeutic_area: 'Dermatology',
    product_type: 'Topical Care',
    image_url: null,
    indications: 'Inflammatory fungal skin infections, eczema, intertrigo, and athlete\'s foot.',
    storage: 'Keep tube tightly closed. Store in a cool place below 25°C.',
    product_info: 'Dual-action cream providing rapid relief from inflammation and itchiness while eradicating fungal infections.',
    is_featured: false,
    display_order: 7,
  },
  {
    id: 'prod-8',
    name: 'OrthoShaw 400',
    slug: 'orthoshaw-400',
    product_code: 'SHA-ORT-008',
    composition: 'Ibuprofen IP 400mg + Paracetamol IP 325mg',
    dosage_form: 'Film-Coated Tablet',
    strength: '400mg + 325mg',
    packaging: '10 x 10 Blister',
    category: 'Analgesic & Anti-inflammatory',
    therapeutic_area: 'Orthopedics',
    product_type: 'Musculoskeletal',
    image_url: null,
    indications: 'Rheumatoid arthritis, osteoarthritis, acute musculoskeletal disorders, and post-operative dental pain.',
    storage: 'Store in a dry place below 25°C.',
    product_info: 'Synergistic combination of NSAID and analgesic for robust pain relief and inflammation control.',
    is_featured: false,
    display_order: 8,
  },
];

export const defaultNewsArticles: NewsArticle[] = [
  {
    id: 'news-1',
    title: 'Shawez Pharma Expands Global R&D Center for Advanced Formulations',
    slug: 'shawez-pharma-expands-global-rd-center',
    excerpt: 'Shawez Pharma inaugurates an expanded state-of-the-art Research & Development facility focusing on novel drug delivery systems.',
    content: 'Shawez Pharma today announced the opening of its expanded R&D center. The facility features advanced analytical instruments, formulation development suites, and high-throughput screening technologies designed to accelerate the delivery of high-quality affordable medicines globally.',
    category: 'Research',
    image_url: null,
    published_date: '2026-08-20',
    is_published: true,
  },
  {
    id: 'news-2',
    title: 'Achieved International Quality Assurance & EU-GMP Compliance',
    slug: 'achieved-eu-gmp-compliance',
    excerpt: 'Our primary manufacturing facility has successfully passed rigorous audit protocols, receiving international WHO-GMP and EU-GMP certifications.',
    content: 'This milestone certification highlights Shawez Pharma\'s continuous dedication to stringent quality control, robust quality management systems, and world-class manufacturing standards across all production lines.',
    category: 'Company News',
    image_url: null,
    published_date: '2026-08-10',
    is_published: true,
  },
  {
    id: 'news-3',
    title: 'Shawez Pharma Launches Expanded Cardiovascular Portfolio',
    slug: 'shawez-pharma-launches-cardiovascular-portfolio',
    excerpt: 'Introducing next-generation antihypertensive and lipid-lowering formulations tailored for global markets.',
    content: 'Shawez Pharma expands its cardiology division with four new high-potency formulations aimed at improving compliance and patient outcomes in chronic cardiovascular management.',
    category: 'Product Updates',
    image_url: null,
    published_date: '2026-07-25',
    is_published: true,
  },
];

export const defaultJobOpenings: JobOpening[] = [
  {
    id: 'job-1',
    title: 'Senior Formulation Scientist',
    slug: 'senior-formulation-scientist',
    department: 'R&D',
    location: 'Corporate R&D Center',
    job_type: 'Full-Time',
    description: 'We are seeking an experienced Formulation Scientist to lead solid oral dosage form development and technology transfer.',
    requirements: 'M.Pharm / Ph.D. in Pharmaceutics with 5+ years of experience in generic drug formulation development.',
    is_active: true,
    posted_date: '2026-08-15',
  },
  {
    id: 'job-2',
    title: 'Quality Assurance Executive',
    slug: 'quality-assurance-executive',
    department: 'Quality Assurance',
    location: 'Manufacturing Plant',
    job_type: 'Full-Time',
    description: 'Responsible for audit compliance, QMS documentation, batch release verification, and regulatory inspection readiness.',
    requirements: 'B.Pharm / B.Sc in Chemistry with 3+ years experience in cGMP pharma QA environment.',
    is_active: true,
    posted_date: '2026-08-12',
  },
  {
    id: 'job-3',
    title: 'Regulatory Affairs Manager',
    slug: 'regulatory-affairs-manager',
    department: 'Regulatory Affairs',
    location: 'Corporate Office',
    job_type: 'Full-Time / Hybrid',
    description: 'Manage international dossier submissions (CTD/eCTD formats) for semi-regulated and regulated export markets.',
    requirements: 'Degree in Pharmacy or Life Sciences with 6+ years in international regulatory submissions.',
    is_active: true,
    posted_date: '2026-08-01',
  },
];
